### ISSUE TITLE
Bump Dahlia

### ISSUE THREAD

**Issue by trag1c** [samarium-lang/Samarium#28]
| ⚠️ Make sure you're contributing to the `0.4.0` branch! |
| --- |

Use [Dahlia](https://github.com/trag1c/Dahlia) 2.0.0 instead of 1.1.0. That's mainly replacing the `dahlia` and `dprint` functions with the new `Dahlia` class.

**Comment by Lunarmagpie** [comment]
I think I might be able to do this :confounded:
