### ISSUE TITLE
Update `core.py` to use `pathlib`

### ISSUE THREAD

**Issue by trag1c** [samarium-lang/Samarium#30]
| ⚠️ Make sure you're contributing to the `0.4.0` branch! |
| --- |

`core.py`'s `import_module` and `run` functions currently use the `os` module for working with paths.

I believe these two can be refreshed with some `pathlib`.

**Comment by Celeo** [comment]
Hi,

What is the "dahlia" dependency listed [here](https://github.com/samarium-lang/Samarium/blob/e8a29b951ed91e8aad6db3b2a4bfff66f97644b0/pyproject.toml#L13)? Poetry on my system cannot find it.

**Comment by trag1c** [comment]
> Hi,
> 
> What is the "dahlia" dependency listed [here](https://github.com/samarium-lang/Samarium/blob/e8a29b951ed91e8aad6db3b2a4bfff66f97644b0/pyproject.toml#L13)? Poetry on my system cannot find it.

Hey, I've also had some issues with it with version resolving in poetry—not sure what's the issue, maybe I set it up incorrectly? Anyway, here's the [repo](https://github.com/trag1c/Dahlia) and the [PyPI page](https://pypi.org/project/dahlia/).
